highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://kyeongan.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Karl Kwon, Ph.D.
name: Karl Kwon, Ph.D.
email: kyeongan.kwon@gmail.com
email_full: mailto:kyeongan.kwon@gmail
website: github.io/kyeongan
website_full: https://kyeongan.github.io/kyeongan
github: kyeongan
twitter: newmkka
tel: +1 (832) 800 8977
tel_full: tel:+18328008977
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 44 Perth Street
postcode: 75001
city: Dallas, Texas
country: USA
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
